### ISSUE TITLE
Ability to observe instructions (setup ContextFactory)

### ISSUE THREAD

**Issue by mrdon** [ringo/ringojs#149]
Because the RhinoEngine uses its own RhinoContextFactory, I'm unable to configure the Context to register an instruction count observer in order to prevent infinite loops and long-running scripts:

http://stackoverflow.com/questions/93911/how-can-you-run-javascript-using-rhino-for-java-in-a-sandbox/754792#754792

Either I'd like to provide a custom ContextFactory through RingoConfiguration or register a class to be called before the Context is returned from the factory.

**Comment by botic** [comment]
I’m closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this / there is no interest in it.

Please reopen if you still encounter this issue with the current master version or there is a need to address this issue.
