### ISSUE TITLE
HttpClient connect/readTimeout return status 500

### ISSUE THREAD

**Issue by kmfdm1** [ringo/ringojs#267]
A connection timing out should not return a http-error-code of 500.
A status-code 500 may only be returned from a proxyserver which is unable to connect to the desired url, or a reverseproxy unable to connect to the backend which then is received by the httpclient which was able to connect to the reverse-/proxy.

We should set the status-code to an invalid http-response-code (0, -1 or undefined for example) and make the exception available in an property of the Exchange-object.

**Comment by botic** [comment]
nginx uses status code `444` inside it's log file to indicate that the server didn't returned a result. We could also assign status code `0` to the exchange object. If a request results in a timeout, the `exchange.done` should not be `true`, since the request has not completed.

I added a timeout test in https://github.com/ringo/ringojs/tree/issues/267

**Comment by botic** [comment]
Another option: leaving the status in the callback with `null` and done could be `false`. The `complete` callback is called in every case.

https://github.com/ringo/ringojs/blob/26a8ae1e8329f03c24ccc33675a3e0b2d81faa08/test/ringo/httpclient_test.js#L657

**Comment by botic** [comment]
Related with #310.

We should fix this issue for 0.12 in an acceptable way and then move the ringo/httpclient into a separate package.

**Comment by botic** [comment]
Timeouts will raise an exception in the following improved branch:
https://github.com/ringo/ringojs/tree/httpclient-drop-callbacks
