### ISSUE TITLE
can not support https??

### ISSUE THREAD

**Issue by guxima** [ringo/ringojs#298]
can not support https??

**Comment by botic** [comment]
For what part of Ringo is this issue? Please specify.

**Comment by guxima** [comment]
sorry~ i just mean how do i use "ringo/httpclient" to send request with "HTTPS"

**Comment by botic** [comment]
Works for me as expected:
https://gist.github.com/botic/437dfb79c5dcab88221c

Can you provide a short gist of your code which fails? Ringo has TLS/SSL support for the includes Jetty server (you have to config the server in the `jetty.xml` config) and in the HTTP client.

**Comment by guxima** [comment]
hi, i send a request "https://xxx.com" by ringo/httpclient and get a tip about cert
require('ringo/httpclient').request(url, option)
can i set cert in option?

**Comment by grob** [comment]
does the website in question use a self-signed certificate? if yes it gets a bit more complex, as you need to create a java keystore with the certificate, otherwise `java.net.URL` used under the hood of ringo's httpclient won't accept it. as an example have a look at the [http client](https://github.com/grob/rp/blob/master/lib/utils/httpclient.js) used by [rp](https://github.com/grob/rp), the ringo package manager client.

**Comment by guxima** [comment]
ok, i'll try it
