### ISSUE TITLE
httpclient: removal of beforeSend callback breaks rp

### ISSUE THREAD

**Issue by grob** [ringo/ringojs#319]
rp currently relies on the `beforeSend` callback in httpclient (removed in ) to define a custom SSL socket factory for the URLConnection used by httpclient which accepts the self-signed certificate ([see here](https://github.com/grob/rp/blob/master/lib/utils/httpclient.js#L103-L107)). this doesn't work anymore as 71c65743ed7b6a91c81dd3bdf752e57a32f3f9de removed the callback.

i'd like to propose to modify the Exchange constructor to accept a URLConnection instance as first argument too, which would allow the same flexibility.

in addition the hardcoded `User-Agent` and `Accept-Encoding` headers should only be used if a url string is passed as first argument, and only if no header values are passed as options to the constructor.

any opinions on that?

**Comment by botic** [comment]
:+1: for providing a custom URL connection instead of a URL string.

It should be possible to override the `User-Agent` and `Accept-Encoding`, which is not the case at the moment.

Btw. JDK9 is likely to provide a very straight forward HttpClient itself: http://cr.openjdk.java.net/~michaelm/8087112/05/apidoc/
