### ISSUE TITLE
add object deep clone utility

### ISSUE THREAD

**Issue by oberhamsi** [ringo/ringojs#334]
deep cloning of objects, arrays, numbers, strings etc.

something like https://github.com/pvorb/node-clone

**Comment by botic** [comment]
This would enhance / replace [ringo/utils/objects clone](http://ringojs.org/api/master/ringo/utils/objects/#clone), or?

**Comment by botic** [comment]
I'm working on a port of node-clone to Ringo. I discovered that Ringo's clone is in the form `clone(object, cloned, recursive)` where `cloned` is a possible target to clone into. Does this make a sense and is actually used? Otherwise I would modify the method to the following form from node-clone: `clone(parent, circular, depth, prototype)` and throw an Error if the second argument is an object. This would break existing code using the < 1.0 parameter order, but at least it's no silent error.

**Comment by botic** [comment]
One of the negative effects of the 0.12 API: `objects.clone()` could be used in the way of `merge()` and this leads to confusing code. Example:

```javascript
const objects = require("ringo/utils/objects");
let x = { foo: "bar" };
let y = { abc: "xyz" };
objects.clone(x,y);
console.dir(x); // { foo: 'bar' }
console.dir(y); // { abc: 'xyz', foo: 'bar' }
```
