### ISSUE TITLE
Implement globbing in fs module

### ISSUE THREAD

**Issue by hns** [ringo/ringojs#41]
(updated title to reflect list*Tree() already implemented)

**Comment by grob** [comment]
I've released two new modules for this:

* [glob](https://github.com/grob/glob), internally using
* [fnmatch](https://github.com/grob/fnmatch)

I didn't want to add to the `fs` module since `fnmatch` can be used on its own, and is quite extensive (the `glob` module itself is small). Please give it a try and let me know what you think about it (and if it's sufficient to close this issue :).

**Comment by botic** [comment]
Looks for me the better approach since there are also the Java globs.
