### ISSUE TITLE
How to setup text editors/IDEs to use with ringo?

### ISSUE THREAD

**Issue by CretinHo** [ringo/ringojs#424]
I tried NetBeans, but it has problems parsing ringo's modules. So it's ended up with a useless bloated editor that do nothing other than syntax highlighting and sometimes gives annoying and incorrect suggestions and errors parsing the modules.

It seems difficult. As ringo is not really pure JS. It has Java mixed in.

How could I have intellisense (code completion) working? Which text editors/IDEs you recommended me to use?

So far I coded simple one file .js program using Geany. It has nice syntax highlighting but no code completion, make writing code in it a pain, boring and tired task.

**Comment by CretinHo** [comment]
This is what I wanted to know most. Most IDEs have JavaScript support but it's HTML5 JS app or NodeJS. Adapt them to use with Ringo is too difficult given my current ability :smile:

**Comment by botic** [comment]
My setup is IntelliJ IDEA and VS Code with standard JavaScript features. You will have to ignore any Node syntax highlighting or warnings, but mostly this is okay. Since Node never adapted the CommonJS module structure, overlapping but incompatible modules like `fs` are most painful.

If you want a perfect IDE and editor experience, RingoJS is not the right choice for you. I would suggest Node and TypeScript as the runtime with the best developer experience available.
