### ISSUE TITLE
Can't use math.js with Ringo

### ISSUE THREAD

**Issue by altPOCA** [ringo/ringojs#428]
Here is math.js: https://mathjs.org/

It's fairly portable as it stated, it works with both the browser and nodejs.

But it doesn't work with Ringo!

I will not give you an example code, download math.js and try yourself.

I'm on the way to remove anything RingoJS related in my stack and replace it with Node.

Sorry. Because of Rhino, Ringo is too useless. Can't you third party JS libraries out there. Seems I have to revert to the Java libraries instead. But if it's about the JVM, who will use such a language as JS? I'm better just use Java directly or Kotlin.

**Comment by botic** [comment]
The primary purpose of Ringo is to leverage Java's strengths, not to be the fastest and most competitive JavaScript runtime.

**Comment by altPOCA** [comment]
> The primary purpose of Ringo is to leverage Java's strengths, not to be the fastest and most competitive JavaScript runtime.

So it seems you wanted to use JS as a glue language only? It's not about performance and competitive, it's about standard compliant. Most of the things I learned in JS books, I can't use it with Ringo because Rhino not yet supported it. Rhino is in maintenance mode and so does Ringo, I was wrong looking here in the first place. Please update your web site to clearly state it's in maintenance mode, because the site appeared to be active and competiting with Node, which is not the case!

https://github.com/mozilla/rhino/issues/835

Look! Rhino is too useless, slow and non-standard compliant, doesn't support modern code.

About leveraging Java libraries, this caused Ringo to be badly supported by JS IDE out there. It should have it own IDE or editor, because it's indeed a mess between Java and legacy JS, most JS IDE will spit out gazillions of errors about of this!

Why someone would use Ringo? Slow. Doesn't support modern language features. Poor IDE support. Code completion is only patially working, and completely non-existent for the Java part.

Enough. Good luck to you maintaining your legacy code because there are many poor people still using it (is there any of them at all?). Bye.

**Comment by botic** [comment]
Sorry for your disappointment, but it is not the case that Ringo or Rhino are in something like a maintenance mode, but both are under development and in active use. If you put the funding for 3 to 5 full-time maintainers on the table, Rhino and Ringo would move forward faster. But it is as it is: Best effort to keep up with modern JS features, but under the given development resources.

If you don't know how to use Java libraries effectively in your IDE of choice, we cannot help out. Most Ringo developers use IntelliJ IDEA and this is a great choice, since it can handle most of the Rhino-specific patterns.
