### ISSUE TITLE
Embedding ringojs interpreter into java project

### ISSUE THREAD

**Issue by ExiaHan** [ringo/ringojs#433]
Hi there,  I want to embed ringojs interpreter into my java project for executing some javascripts and retrieving the result back to java code for further processing.

I've  searched a lot for how to integrate it into java, but all of them are about how to load jar files into ringo runtime, not import ringojs into java project. 

So I wonder if there any docs about how to invoke ringojs in java project?
Thanks!

**Comment by botic** [comment]
You can look at https://github.com/ringo/ringojs/tree/master/src/org/ringojs/tools and the classes there. Also the JSGI Servlet, which maps HTTP requests to Ringo scripts, should be a good starting point: https://github.com/ringo/ringojs/blob/master/src/org/ringojs/jsgi/JsgiServlet.java

We don't have an embedding guide in place, since most current use cases are standalone Ringo instances or inside a Servlet container / application server.

**Comment by ExiaHan** [comment]
> You can look at https://github.com/ringo/ringojs/tree/master/src/org/ringojs/tools and the classes there. Also the JSGI Servlet, which maps HTTP requests to Ringo scripts, should be a good starting point: https://github.com/ringo/ringojs/blob/master/src/org/ringojs/jsgi/JsgiServlet.java
> 
> We don't have an embedding guide in place, since most current use cases are standalone Ringo instances or inside a Servlet container / application server.

Hi @botic ,
Thanks for your replying, I'll read the code you mentioned to try to find out the way.
Thanks again for your help. :)
