### ISSUE TITLE
Breakage in jsdoc if repository contains symlinked paths

### ISSUE THREAD

**Issue by oberhamsi** [ringo/ringojs#80]
Repository overview works but links to symlinked modules are broken.

Something is wrong with the way it generates the moduleid (and therefor links) for those symlinked modules. Jsdoc seems to use absolute paths instead of relative to repository.

**Comment by botic** [comment]
I’m closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this / there is no interest in it.

Please reopen if you still encounter this issue with the current master version or there is a need to address this issue.
