### ISSUE TITLE
Resolve failing compliance tests for CommonJS Unit Testing/1.0

### ISSUE THREAD

**Issue by earl** [ringo/ringojs#83]
The compliance testsuite for CommonJS Unit Testing/1.0 originally committed in 5583f2c9570e49c92391a66ad4487ab84cb9c30b contained three tests that have failed ever since, making our whole testsuite fail. Those failing tests have been now disabled in 1e493de91c4a423821d37321c610add15557d93c disabled.

Some discussion of why those tests fail can be found in the [2010-06-17 IRC logs](http://ringojs.net/bot/2010-06-17). Basically it's due to vague/under-/ill-specified corner cases. Eventually we should work out what to do with those cases and either remove or re-enable those test cases.

**Comment by botic** [comment]
I’m closing this issue because it has been inactive for a long time. This probably means that it is not reproducible or it has been fixed in a newer version. If it’s an enhancement and hasn’t been taken on for so long, then it seems no one has the time to implement this / there is no interest in it.

Please reopen if you still encounter this issue with the current master version or there is a need to address this issue.
